author = "Andx";
name = "Camo Faces Redux [Beta]";
description = "Camo Faces Redux [Beta] - Version {version}";
overview = "Camo Faces Redux is a Rewrite of the Camo Faces Mod, which enables Players to camouflage their faces in Arma3";
overviewPicture = "img\cfr_logo_ca.paa";
picture = "img\cfr_logo_ca.paa";
logo = "img\cfr_icon_ca.paa";
logoOver = "img\cfr_icon_ca.paa";
actionName = "GitHub";
action = "https://github.com/Andx667/CamoFacesRedux";
dlcColor[] = { 0.42, 0.40, 0.00, 1 }; // Olive/khaki (RGBA) — color used for DLC stripes and backgrounds
