#!/usr/bin/env python3

# CAMO GENERATOR - STAGE 5: REGISTRY
# ----------------------------------
# Writes addons/faces/CfgCamoRegistry.hpp: the CfgCamoBaseFaces / CfgCamoSchemes entries that
# tell cfr_common which faces exist and which camo face each scheme maps them to. This is the
# same config extension any other addon uses to register faces (see addons/common/README.md,
# "Extending the mod"), so the mod's own faces go through the public mechanism.
#
# The CfgFaces classes in Faces_*.hpp are the source of truth: every `class GVAR(<face>_<Scheme>)`
# is one pair, so running this after generate_config.py picks up new heads with no further edits.
# Only the DLC gate needs outside knowledge, and that comes from faces.py (APPID). The Marksmen
# faces Bohemia made are not CFR classes and live by hand in CfgCamoVanilla.hpp instead.
#
# Idempotent: it rewrites the whole file every time.

import re

from faces import APPID, NEW, SCHEME_NAMES
from paths import ADDON

# longest first, so "USStripes" is never mistaken for a face called "US" + "Stripes"
SUFFIXES = sorted((suffix for suffix, _, _ in SCHEME_NAMES.values()), key=len, reverse=True)
CLASS_RE = re.compile(r"^class GVAR\((\w+)\)", re.M)

DLC_OF = {f.cls: APPID[f.dlc] for f in NEW.values()}


def split(name):
    for suffix in SUFFIXES:
        if name.endswith("_" + suffix):
            return name[: -len(suffix) - 1], suffix
    raise ValueError(f"{name}: not <face>_<scheme> for any known scheme")


def main():
    bases, pairs = [], {}
    for path in sorted(ADDON.glob("Faces_*.hpp")):
        for name in CLASS_RE.findall(path.read_text(encoding="utf-8")):
            base, scheme = split(name)
            if base not in bases:
                bases.append(base)
            pairs.setdefault(scheme, []).append((base, name))

    out = [
        "// GENERATED by tools/camo_generator/generate_registry.py from the classes in Faces_*.hpp - do",
        "// not edit by hand. Registers CFR's own faces with cfr_common through the same config extension",
        "// any other addon would use; see addons/common/CfgCamo.hpp for what each class means.",
        "",
        "class CfgCamoBaseFaces {",
    ]
    for base in bases:
        if base in DLC_OF:
            out.append(f"    class {base} {{ requiredDLC = {DLC_OF[base]}; }};")
        else:
            out.append(f"    class {base} {{}};")
    out += ["};", "", "class CfgCamoSchemes {"]
    for _, (scheme, _, _) in SCHEME_NAMES.items():
        out.append(f"    class {scheme} {{")
        out.append("        class Faces {")
        for base, name in pairs.get(scheme, []):
            out.append(f"            {base} = QGVAR({name});")
        out += ["        };", "    };"]
    out += ["", "    // Bohemia's own Marksmen faces, written by hand", '    #include "CfgCamoVanilla.hpp"', "};"]

    dest = ADDON / "CfgCamoRegistry.hpp"
    dest.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(bases)} base faces, {sum(len(v) for v in pairs.values())} pairs -> {dest.name}")


if __name__ == "__main__":
    main()
