name = "Camo Faces Redux"
author = "Andx"
prefix = "cfr"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.publish]
description = "workshop/steam_description.md"
changelog = "CHANGELOG.md"

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "img/cfr_icon.png",
    "img/cfr_icon_ca.paa",
    "img/cfr_logo.png",
    "img/cfr_logo_ca.paa",
    "LICENSE",
    "README.md",
    "authors.txt",
]
exclude = []

[properties]
author = "Andx"
